### ISSUE TITLE
Store SFPs MAC address in picozed QSPI to be passed to FPGA SFP config register

### ISSUE THREAD

**Issue by GTHIBAUX** [PandABlocks/PandABlocks-server#1]
Should it be possible to add the readout of SFPs MAC address in picozed QSPI files to be passed to FPGA SFP config register?

**Comment by Araneidae** [comment]
This has been implemented in the server as of commits 1bc5a75 and 241dbb4, but the FPGA support is still under development.  We may also want a rootfs update to help with the installation of the MAC.FPGA file.
This is all managed under DLS Jira ticket BC-709.

**Comment by Araneidae** [comment]
@thomascobb, is this done now?

**Comment by thomascobb** [comment]
Yes
