### ISSUE TITLE
Inconsistencies in numeric parsing on some fields

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [PandABlocks/PandABlocks-server#22]
While checking what types all the fields and attributes are in a PandA, which I'm doing by setting int or float values on the command line and seeing what happens, I noted an odd difference in behaviour between fields and attributes when it comes to setting the wrong value type.

For a bit_mux field's DELAY attribute I can set a floating point value, despite the field itself apparently being an integer:
```
< CLOCK1.ENABLE.DELAY?
OK =0
< CLOCK1.ENABLE.DELAY=3.5
OK
< CLOCK1.ENABLE.DELAY?
OK =3

```
For a param-int field I am unable to set a floating point value and see an error message:
```
< COUNTER1.START?
OK =0
< COUNTER1.START=1.5
ERR Unexpected character after input
< COUNTER1.START=1
OK
```
@Araneidae responded to this in an email:

That's a straightforward bug in the handling for this attribute, there needs to be a parse_eos() call after the parse_uint() call on line 196 of bit_out.c.

Unfortunately, to fix this properly I'll need to check all parses; this is unlikely to be the only error of this kind.  In a lot of the fields parsing and putting are separated, and parsers don't need to check for end of string because that's already done for them by the caller.  For example param fields are implemented via this code (type_put() in types .c):

```
type->methods->parse(type->type_data, number, &string, &value)  ?:
parse_eos(&string)  ?:
write_type_register(type, number, value);
```

This kind of structure can't sensibly be implemented across the board, and it certainly wouldn't be worth the churn, so I'll just have to look through the code.

**Comment by Araneidae** [comment]
Fixed in commit 5c25cb31ab43161018c1a301ec517c49066b1844.  This turns out to be the only error of this type, as far as I can see.
