### ISSUE TITLE
Drop `UNSCALED` data processing format for data capture

### ISSUE THREAD

**Issue by thomascobb** [PandABlocks/PandABlocks-server#24]
From https://pandablocks-server.readthedocs.io/en/latest/capture.html#capture-options

We currently use `SCALED` and `RAW` data processing format. We don't currently use `UNSCALED` and it doesn't make sense for Std Dev.

@shu-soleil do you use `UNSCALED`? Can we drop it?

**Comment by Araneidae** [comment]
This will involve changing the definition of `BARE` which is currently equivalent to
```
UNFRAMED UNSCALED NO_HEADER NO_STATUS ONE_SHOT
```
Perhaps the appropriate alternative is `RAW`.

**Comment by shu-soleil** [comment]
Hello, No we use only SCALED and RAW

> @shu-soleil do you use `UNSCALED`?

**Comment by Araneidae** [comment]
Implemented in PR #25
