### ISSUE TITLE
driver code compile at ARM Debian 9 rootfs

### ISSUE THREAD

**Issue by kimanha** [PandABlocks/PandABlocks-server#3]
Hi,

I am used ARM Debian 9 rootfs for compile driver code and found error.
If comment out the line 129 and 130 the successfully compiled.

root@microjed-sG:/home/kha/PandA/PandABlocks-server# make driver
make -C /lib/modules/4.19.0-xilinx-v2019.1/build M=/home/kha/PandA/PandABlocks-server/build/driver modules \
            ARCH=arm CROSS_COMPILE=
make[1]: Entering directory '/lib/modules/4.19.0-xilinx-v2019.1/build'
  CC [M]  /home/kha/PandA/PandABlocks-server/build/driver/panda_core.o
/home/kha/PandA/PandABlocks-server/build/driver/panda_core.c:129:35: error: array type has incomplete element type 'struct of_device_id'
         .of_match_table = (struct of_device_id[]) {
                                   ^~~~~~~~~~~~
/home/kha/PandA/PandABlocks-server/build/driver/panda_core.c:130:15: error: field name not in record or union initializer
             { .compatible = "xlnx,panda-pcap-1.0", },
               ^
/home/kha/PandA/PandABlocks-server/build/driver/panda_core.c:130:15: note: (near initialization for '(anonymous)')
scripts/Makefile.build:305: recipe for target '/home/kha/PandA/PandABlocks-server/build/driver/panda_core.o' failed
make[2]: *** [/home/kha/PandA/PandABlocks-server/build/driver/panda_core.o] Error 1
Makefile:1517: recipe for target '_module_/home/kha/PandA/PandABlocks-server/build/driver' failed
make[1]: *** [_module_/home/kha/PandA/PandABlocks-server/build/driver] Error 2
make[1]: Leaving directory '/lib/modules/4.19.0-xilinx-v2019.1/build'
Makefile:71: recipe for target '/home/kha/PandA/PandABlocks-server/build/driver/panda.ko' failed
make: *** [/home/kha/PandA/PandABlocks-server/build/driver/panda.ko] Error 2

**Comment by Araneidae** [comment]
There is something very fishy about this.

1. You're building as root.  *Never* do this.
2. You've not set or you've unset `CROSS_COMPILE`.

You should be building with `arm-xilinx-linux-gnueabi-` as the `CROSS_COMPILE` prefix: this is defined in the top level `Makefile`, so you've clearly unset it somewhere.

**Comment by kimanha** [comment]
bpmlab2 ~/xilinx/kiman/PandA/PandABlocks-server $ make driver
Makefile:66: *** Define KERNEL_DIR in CONFIG file.  Stop.

I did not installed Kernel and where can I  download Kernel source?

**Comment by Araneidae** [comment]
If you're trying to rebuild PandA you'll need the [rootfs repository](https://github.com/PandABlocks/PandABlocks-rootfs) and the required [build assets](http://www.ohwr.org/attachments/download/5133/rootfs-tarfiles-0.6.tar) linked from [here](https://pandablocks-rootfs.readthedocs.io/en/latest/building.html).

Ultimately you'll also need the [PandABlocks-FPGA](https://github.com/PandABlocks/PandABlocks-FPGA) repository.

**Comment by Araneidae** [comment]
Assuming you're trying to target a completely different system, the following may be helpful.

The problem you're reporting is something to do with a change in the kernel API from our kernel version (looks like our kernel is quite old, something like 3.18) to your 4.19 version.  It's quite possible that simply adding `#include <linux/mod_devicetable.h>` at the top of `panda_core.c` may be enough; if so, let me know and I'll add this to our source.

**Comment by kimanha** [comment]
Yes, your right. 
I am using the latest kernel version for my test (Kernel 4.19 and Debian 9 rootfs).

After adding "#include <linux/mod_devicetable.h>" now I can compile successfully.

kha@microjed-sG:~/PandA/PandABlocks-server$ make driver
make -C /lib/modules/4.19.0-xilinx-v2019.1/build M=/home/kha/PandA/PandABlocks-server/build/driver modules \
            ARCH=arm CROSS_COMPILE=
make[1]: Entering directory '/lib/modules/4.19.0-xilinx-v2019.1/build'
  CC [M]  /home/kha/PandA/PandABlocks-server/build/driver/panda_core.o
  CC [M]  /home/kha/PandA/PandABlocks-server/build/driver/panda_map.o
  CC [M]  /home/kha/PandA/PandABlocks-server/build/driver/panda_block.o
  CC [M]  /home/kha/PandA/PandABlocks-server/build/driver/panda_stream.o
  LD [M]  /home/kha/PandA/PandABlocks-server/build/driver/panda.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/kha/PandA/PandABlocks-server/build/driver/panda.mod.o
  LD [M]  /home/kha/PandA/PandABlocks-server/build/driver/panda.ko
make[1]: Leaving directory '/lib/modules/4.19.0-xilinx-v2019.1/build'
touch /home/kha/PandA/PandABlocks-server/build/driver/panda.ko

**Comment by kimanha** [comment]
This way is not cross-compile.

My way is to create a Kernel used petalinux and build Debian rootfs.
I am running zynq Debian environment for local compile.

But I am trying to cross-compile the same as you did, but little bit complicated for me.

Thanks,

**Comment by Araneidae** [comment]
Ok, I'll add this line to `panda_core.c` and close this.
