### ISSUE TITLE
Time field's MIN attribute is not reported by *CHANGES?

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [PandABlocks/PandABlocks-server#30]
If you update the `UNITS` of a `time` field, performing `*CHANGES?` will retrieve both the changed `UNITS` value and the updated value of the field itself in the new units, but will not report the changed `MIN` value. For example:

```
< PULSE1.DELAY.UNITS=us
OK
< *CHANGES?
!PULSE1.DELAY=100000
!PULSE1.DELAY.UNITS=us
```

This leads to an odd situation where a client who is polling using `*CHANGES?` (such as my [SoftIOC integration](https://github.com/PandABlocks/PandABlocks-client/pull/28) on the PandA-Client) must perform an extra query to retrieve the new value of `MIN`. 

It seems sensible that the changed `MIN` value should also be reported via `*CHANGES?` requests.

**Comment by Araneidae** [comment]
This issue is affected by #48, if we drop min_value support the `.MIN` attribute will simply disappear.
