### ISSUE TITLE
Add `start_time` to docs

### ISSUE THREAD

**Issue by coretl** [PandABlocks/PandABlocks-server#43]
#34 added `start_time` to header, this needs to be added to the docs:

https://github.com/PandABlocks/PandABlocks-server/blob/54227ee2c98dbdfa2758eea450f95dff6601be82/server/prepare.c#L305

**Comment by EmilioPeJu** [comment]
https://github.com/PandABlocks/PandABlocks-FPGA/issues/172 addresses this
