### ISSUE TITLE
Add timestamp to header

### ISSUE THREAD

**Issue by thomascobb** [PandABlocks/PandABlocks-server#7]
Currently PCAP has relative timestamps for things like TS_CAPTURE. MAX IV would like to relate this to an absolute timestamp that is provided in the header of the capture. This can be provided by NTP now, but in the future may be provided by the timestamp from the EVR.

**Comment by Araneidae** [comment]
I like the approach suggested by @valerixb, but this leaves open the question of when capture actually started.  Will the ARM timestamp be enough to solve this, or are we also going to want the driver to capture a timestamp when capture begins?  This may be tricky, as data only starts to arrive after a buffer's worth has been seen, or a timeout.

**Comment by thomascobb** [comment]
How about this, for now we add `pcap_arm_time` which is accurate to NTP (a couple of ms?). In the future we can add a second `pcap_enable_time` which is raised as an interrupt when PCAP.ENABLE goes high after an ARM, which is accurate to the latency of getting an interrupt into the ARM (not sure how accurate this is?)

**Comment by Araneidae** [comment]
Sounds good to me.  We'd have to add an ENABLE interrupt, or capture a hardware timestamp in firmware.

**Comment by coretl** [comment]
https://github.com/PandABlocks/PandABlocks-FPGA/issues/88 needs to be done first
